### ISSUE TITLE
Misaligned Text (VGA)

### ISSUE THREAD

**Issue by rldald989** [midas-os/MidAS#17]
**Describe the bug**
When inputting a newline character into the ``write_str_centered_x`` function in VGA Mode the whole text gets misaligned.

**To Reproduce**
1. Go to 'vga_driver.rs'.
2. Use \n in a ``write_str_centered_x`` call.
3. You should see misaligned text.

**Expected behavior**
I expected the text to be outputted in the middle, but it went out of bounds.

```rs
fn my_page() {
    /*******************
    * Buggy Code Start
    *******************/

    write_str_centered_x(box_start_u, box_end_u, box_start_u.1 + 20, "Hepha Engine", Color16::LightGreen);

    write_str_centered_x(box_start_u, box_end_u, box_start_u.1 + 40, "Lorem ipsum dolor sit amet, \nconsectetur adiüiscing elit.", Color16::LightRed);
    write_str_centered_x(box_start_u, box_end_u, box_start_u.1 + 80, "Praesent velit sem, viverra \net elit quis, euismod euismod lectus.", Color16::LightRed);

    /******************
    * Buggy Code End
    ******************/
}
```
![Screenshot_20230214_041202](https://user-images.githubusercontent.com/70861085/218875445-a739aae8-61ef-426a-84f2-5de4485ebfdf.png)

**Comment by MindlessSea** [comment]
Will investigate

**Comment by MindlessSea** [comment]
Hey there, may I see the whole function so I can find the bug/replicate it easier?

**Comment by MindlessSea** [comment]
Updated issue to explain the issue in more detail and replaced the code screenshot with a code block

**Comment by MindlessSea** [comment]
Fixed in [this commit](https://github.com/midas-os/MidAS/commit/0bef1cf54546ce172df9a6c6e1e0114eed93447f)!
Thank you for reporting this bug!
